version: "3"

services:
  backend:
    container_name: "blog-engine-backend"
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    env_file: ".env"
    environment:
      - 'PGHOST=postgres'
    depends_on:
      - postgres


  postgres:
    container_name: "blog-engine-postgres"
    image: "postgres:12"
    ports:
      - "3300:3300"
    env_file: .env

volumes:
  data_backend_libs:
    driver: local
